// Capture lock query + cap-name <-> bit-index mapping.
//
// The bit-index table (capture_table.h) is generated by
// scripts/sync_capture_table.ps1 from apworld/data/items.json so the Switch
// and bridge cannot drift on cap-name <-> id assignment.

#pragma once

#include <cstdint>
#include <string>

namespace smoap::game {

// Returns the bit index for `cap_name` (matching apworld's enemy ordering)
// or 0xff if the name is unknown.
std::uint8_t captureBitFor(const std::string& cap_name);

// M6 phase B: write `hack_name` into SMO's hack dictionary so the capture
// shows as unlocked in the compendium (and is treated as known by gameplay).
// Idempotent — probes isExistInHackDictionary first; the GameDataFunction
// API itself is a no-op on duplicates anyway.
//
// Inputs:
//   cap_name  — apworld-canonical cap name (e.g. "Goomba"). Used for logging.
//   hack_name — raw SMO hack name (e.g. "Kuribo"). What goes into the game.
//
// Call from the game frame thread only. Requires the GameDataHolder* cache
// in ApState to be populated (DrawMainHook does this every frame).
//
// resolveCaptureGrantSymbols() must be called once at module init (from
// installCaptureGrantSymbols below) to bind the GameDataFunction:: function
// pointers via nn::ro::LookupSymbol. If the lookup fails, grantCapture logs
// and drops.
void grantCapture(const std::string& cap_name, const std::string& hack_name);

// Resolve the addHackDictionary + isExistInHackDictionary symbols once at
// module init. Wired from main.cpp alongside the existing softInstall calls.
void installCaptureGrantSymbols();

// True if the player has *not* received the unlock item for this capture.
bool captureBlocked(const std::string& cap_name);

// Resolve the capture's canonical name from a PlayerHackData / hack-target.
// (Implementation pulls from sead string tables in the game.)
std::string nameForHackData(/* const PlayerHackData* data */);

// Plays the standard "no" SE used by the game when something is denied.
void playSE_NG();

// M4.5 reconciliation: enumerate every capture (hack) the player has currently
// unlocked AND has used at least once. Worker-thread call from
// ApClient::sendSnapshot. Emits raw hack_names that the bridge resolves via
// capture_map.json.
//
// Stub for M4.5; M5/M6 fills in via GameDataHolder. The current ApState
// captures_unlocked bitset only tracks AP-granted captures, not save-state.
using CaptureEnumerationCallback = void(*)(void* ctx, const char* hack_name);
void enumerateOwnedCaptures(CaptureEnumerationCallback cb, void* ctx);

}  // namespace smoap::game
