"""`.smoap` file: per-player metadata generated by AP world-gen.

The `.smoap` file is the user-facing entry point. Generated per-player when
the multiworld is created (see `ManualWorld.generate_output` in the apworld's
`__init__.py`), shipped inside the per-player zip alongside the standard AP
artifacts. The user double-clicks it; Archipelago Launcher resolves the file
extension via `SuffixIdentifier('.smoap')` in the Component registration and
hands the path to `launch_smo_client`, which:

  - If first-time-setup hasn't been completed: spawns the wizard, passing the
    `.smoap` path so it can hand off to SMOClient on completion.
  - If setup IS complete: parses the .smoap directly and launches SMOClient
    with `--name` (and optionally `--connect`) pre-filled, so the user lands
    in the Connect bar ready to go.

The format is intentionally tiny — just enough to identify *which slot* this
player is. Everything else (bridge IP, deploy target, paths) is per-machine
state managed by the setup wizard. AP server address is optional because the
generator's host may not know it (self-hosted vs archipelago.gg vs ...);
SMOClient will prompt via the Connect bar when it's empty.

Schema is versioned so future fields can land without breaking older clients.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

SMOAP_SCHEMA_VERSION = 1
GAME_NAME = "Spicy Meatball Overdrive"


@dataclass
class SmoapFile:
    """In-memory form of a `.smoap` file.

    `server_address` and `password` may be empty strings — SMOClient will
    fall back to the Connect-bar prompt in that case.
    """
    slot_name: str
    seed_name: str = ""
    server_address: str = ""
    password: str = ""
    game: str = GAME_NAME
    version: int = SMOAP_SCHEMA_VERSION

    def to_dict(self) -> dict[str, Any]:
        return {
            "game": self.game,
            "version": self.version,
            "slot_name": self.slot_name,
            "seed_name": self.seed_name,
            "server_address": self.server_address,
            "password": self.password,
        }

    def to_json(self) -> str:
        # `sort_keys=False` keeps the human-readable order — `game` and
        # `version` first so a human eyeballing the file knows what it is.
        return json.dumps(self.to_dict(), indent=2)

    def write(self, path: Path) -> None:
        path.write_text(self.to_json(), encoding="utf-8")


def parse_smoap(text_or_path: str | Path) -> SmoapFile:
    """Read a `.smoap` file (path or raw JSON text) and return a SmoapFile.

    Raises `ValueError` for malformed JSON, missing required fields, or an
    unknown game/version combination. Forward-compatible: unknown keys are
    silently ignored so a future-version client can add fields without
    breaking older ones (game/version mismatch is the explicit break point).
    """
    if isinstance(text_or_path, Path):
        text = text_or_path.read_text(encoding="utf-8")
    else:
        # Heuristic: if it starts with `{` it's JSON; otherwise treat as path.
        # (Pure-JSON callers always pass via Path or wrap their JSON in
        # this string form intentionally; this branch lets tests pass raw
        # JSON without bouncing off the filesystem.)
        s = text_or_path.lstrip()
        if s.startswith("{"):
            text = text_or_path
        else:
            text = Path(text_or_path).read_text(encoding="utf-8")

    try:
        d = json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(f"invalid JSON: {e}") from e

    if not isinstance(d, dict):
        raise ValueError("expected JSON object")

    game = d.get("game")
    if game != GAME_NAME:
        raise ValueError(
            f"unexpected game={game!r}; this .smoap is not for {GAME_NAME!r}"
        )

    version = d.get("version")
    if not isinstance(version, int) or version < 1:
        raise ValueError(f"missing or invalid version={version!r}")
    if version > SMOAP_SCHEMA_VERSION:
        raise ValueError(
            f"smoap version {version} is newer than client supports "
            f"({SMOAP_SCHEMA_VERSION}); upgrade SMO Archipelago"
        )

    slot_name = d.get("slot_name") or ""
    if not isinstance(slot_name, str) or not slot_name:
        raise ValueError("slot_name is required and must be a non-empty string")

    return SmoapFile(
        slot_name=slot_name,
        seed_name=str(d.get("seed_name") or ""),
        server_address=str(d.get("server_address") or ""),
        password=str(d.get("password") or ""),
        game=game,
        version=version,
    )


def smoap_to_launch_args(s: SmoapFile) -> list[str]:
    """Translate a SmoapFile into SMOClient CLI args (`--name`, `--connect`,
    `--password`).

    Empty fields are omitted — SMOClient already handles missing `--connect`
    by leaving the GUI Connect bar blank, and missing `--name` by leaving
    `ctx.auth` unset until the user types one.
    """
    out: list[str] = ["--name", s.slot_name]
    if s.server_address:
        out += ["--connect", s.server_address]
    if s.password:
        out += ["--password", s.password]
    return out
